FACILITY_LIST = [
    ("Yale New Haven Hospital", "New Haven", "CT"),
    ("Geisinger Medical Center", "Danville", "PA"),
    ("Christiana Care Health Services", "Newark", "DE"),
    ("Augusta University Medical Center", "Augusta", "GA"),
    ("Cincinnati Children's Hospital Medical Center", "Cincinnati", "OH"),
    ("City of Hope National Medical Center", "Duarte", "CA"),
    ("VA Tennessee Valley Healthcare System", "Nashville", "TN"),
    ("University of Tennessee Medical Center", "Knoxville", "TN"),
    ("Nemours Children's Hospital in Delaware", "Wilmington", "DE"),
    ("UVA Health", "Charlottesville", "VA"),
    ("University of Michigan Medical Center", "Ann Arbor", "MI"),
    ("Corewell Health", "Grand Rapids", "MI"),
    ("UNM Comprehensive Cancer Center", "Albuquerque", "NM"),
    ("The Jewish Hospital", "Cincinnati", "OH"),
    ("Children's Hospital", "New Orleans", "LA"),
    ("Medical University of South Carolina", "Charleston", "SC"),
    ("Levine Children's Hospital", "Charlotte", "NC"),
    ("UNC Hospitals", "Chapel Hill", "NC"),
    ("Baylor University Medical Center", "Dallas", "TX"),
    ("UCSF Benioff Children's Hospital", "Oakland", "CA"),
    ("Nicklaus Children's Hospital", "Miami", "FL"),
    ("Roger Williams Medical Center", "Providence", "RI"),
    ("Massachusetts General Hospital", "Boston", "MA"),
    ("H. Lee Moffitt Cancer Center", "Tampa", "FL"),
    ("Oregon Health & Science University", "Portland", "OR"),
    ("Nebraska Medicine", "Omaha", "NE"),
    ("MD Anderson Cancer Center", "Houston", "TX"),
    ("Fred Hutchinson Cancer Center", "Seattle", "WA"),
    ("Karmanos Cancer Center", "Detroit", "MI"),
    ("Akron Children's Hospital", "Akron", "OH"),
    ("Memorial Sloan Kettering Cancer Center", "New York", "NY"),
    ("Ann & Robert Lurie Children's Hospital", "Chicago", "IL"),
    ("Baptist Cancer Center", "Memphis", "TN"),
    ("Banner MD Anderson Cancer Center", "Gilbert", "AZ"),
    ("Covenant Health System Transplant Program", "Lubbock", "TX"),
    ("Baylor Scott & White Medical Center", "Temple", "TX"),
    ("Emory University Hospital", "Atlanta", "GA"),
    ("Mayo Clinic Florida", "Jacksonville", "FL"),
]

# US State mappings - full names to abbreviations
STATE_MAPPINGS = {
    "alabama": "AL",
    "alaska": "AK",
    "arizona": "AZ",
    "arkansas": "AR",
    "california": "CA",
    "colorado": "CO",
    "connecticut": "CT",
    "delaware": "DE",
    "florida": "FL",
    "georgia": "GA",
    "hawaii": "HI",
    "idaho": "ID",
    "illinois": "IL",
    "indiana": "IN",
    "iowa": "IA",
    "kansas": "KS",
    "kentucky": "KY",
    "louisiana": "LA",
    "maine": "ME",
    "maryland": "MD",
    "massachusetts": "MA",
    "michigan": "MI",
    "minnesota": "MN",
    "mississippi": "MS",
    "missouri": "MO",
    "montana": "MT",
    "nebraska": "NE",
    "nevada": "NV",
    "new hampshire": "NH",
    "new jersey": "NJ",
    "new mexico": "NM",
    "new york": "NY",
    "north carolina": "NC",
    "north dakota": "ND",
    "ohio": "OH",
    "oklahoma": "OK",
    "oregon": "OR",
    "pennsylvania": "PA",
    "rhode island": "RI",
    "south carolina": "SC",
    "south dakota": "SD",
    "tennessee": "TN",
    "texas": "TX",
    "utah": "UT",
    "vermont": "VT",
    "virginia": "VA",
    "washington": "WA",
    "west virginia": "WV",
    "wisconsin": "WI",
    "wyoming": "WY",
}

# Valid state abbreviations
STATE_ABBREVIATIONS = set(STATE_MAPPINGS.values())
